khu-khlug/sight-backend

codecov.yml, src/sight/app.service.spec.ts
**주요 변경 사항**
- 커버리지 변화를 위한 뺄셈 테스트 추가
=> test: 뺄셈 테스트 추가

src/app/domain/adapter/ISlackSender.ts, src/app/domain/message/model/constant.ts
슬랙 메시지 전송 인터페이스와 슬랙 메시지 카테고리 상수를 추가하였습니다.
이후 슬랙 메시지를 보내야 할 상황이 있을 때, 먼저 인터페이스를 사용하도록 하기 위해서입니다.
=> feat: 슬랙 메시지 전송 인터페이스 추가

README.md
README에서 codecov 뱃지를 제거하고 기술 스택을 추가하였습니다.
더 이상 codecov를 사용하지 않습니다.
=> docs: 기술 스택 추가

src/app/domain/user/model/User.spec.ts
유저 도메인에 대한 테스트를 추가합니다.
추가된 로직이 테스트에 반영되지 않았습니다.
=> test: 유저 도메인에 대한 테스트 추가

src/app/domain/group/model/Group.ts, src/app/domain/group/model/GroupBookmark.ts, src/app/domain/group/model/GroupCard.ts, src/app/domain/group/model/GroupList.ts, src/app/domain/group/model/GroupLog.ts, src/app/domain/group/model/GroupMember.ts, src/app/domain/group/model/GroupRecord.ts, src/app/domain/group/model/SavedRecord.ts, src/app/domain/group/model/constant.ts, src/app/domain/interest/model/GroupInterest.ts, src/app/domain/seminar/model/Seminar.ts, src/app/domain/seminar/model/SeminarRegistration.ts, src/app/domain/seminar/model/constant.ts
그룹 관련 도메인 모델을 구현합니다.
그룹 관련 기능을 구현하기 위함입니다.
=> feat: 그룹 관련 도메인 구현

src/__test__/fixtures/view/group.ts, src/app/application/group/query/IGroupQuery.ts, src/app/application/group/query/listGroupMember/ListGroupMemberQuery.ts, src/app/application/group/query/listGroupMember/ListGroupMemberQueryHandler.spec.ts, src/app/application/group/query/listGroupMember/ListGroupMemberQueryHandler.ts, src/app/application/group/query/listGroupMember/ListGroupMemberQueryResult.ts, src/app/application/group/query/view/GroupMemberListView.ts, src/app/application/group/query/view/GroupMemberView.ts, src/app/application/user/command/updateUser/UpdateUserCommandHandler.ts
그룹 멤버 목록 조회 기능을 구현합니다.
기존 기능 구현을 위함입니다.
=> feat: 그룹 멤버 목록 조회 구현

src/app/application/group/command/changeGroupState/ChangeGroupStateCommandHandler.spec.ts, src/app/application/group/command/changeGroupState/ChangeGroupStateCommandHandler.ts, src/app/application/group/eventHandler/GroupPortfolioEnabledHandler.ts, src/app/application/group/eventHandler/GroupUpdatedHandler.spec.ts, src/app/application/group/eventHandler/GroupUpdatedHandler.ts, src/app/infra/logger/GroupLogger.spec.ts, src/app/infra/logger/GroupLogger.ts
https://github.com/khu-khlug/sight-backend/pull/50 에서 구현한 그룹 로거를 사용하여 로그를 생성하도록 수정합니다.
이외 이모저모 리팩토링도 했어요.
그룹 로거 쓸려고 만들어서.. 이제 씁니다..
=> refactor: 그룹 로거를 사용하도록 수정 및 이모저모 리팩토링

.github/workflows/coverage.yml, README.md
main 브랜치에 머지했을 때도 coverage를 확인하도록 수정합니다.
coveralls에 기록을 남기기 위함입니다.
=> ci: main 브랜치에 머지했을 때도 coverage를 확인하도록 수정

.github/workflows/test.yml
`test.yml` 워크플로우의 액션 버전도 업그레이드합니다.
relates to: #65
=> ci: test 워크플로우의 액션 버전 업그레이드

package-lock.json, package.json, src/__test__/fixtures/CacheFixture.ts, src/app.module.ts, src/app/application/infraBlue/command/updateDoorLockPassword/UpdateDoorLockPasswordCommand.ts, src/app/application/infraBlue/command/updateDoorLockPassword/UpdateDoorLockPasswordCommandHandler.spec.ts, src/app/application/infraBlue/command/updateDoorLockPassword/UpdateDoorLockPasswordCommandHandler.ts, src/constant/message.ts, src/util/validator/ClassValidator.spec.ts, src/util/validator/ClassValidator.ts, src/util/validator/ValidationFailedException.ts
도어락 비밀번호 업데이트 커맨드 핸들러를 구현합니다.
기존 기능 구현
=> feat: 도어락 비밀번호 업데이트 구현

src/RootModule.ts, src/app/AppModule.ts, src/app/interface/infraBlue/manager/InfraBlueManageController.ts, src/app/interface/infraBlue/manager/dto/GetDoorLockPasswordResponseDto.ts, src/app/interface/infraBlue/manager/dto/UpdateDoorLockPasswordRequestDto.ts, src/app/interface/util/DtoBuilder.ts, src/main.ts
도어락 비밀번호 관련 컨트롤러를 구현합니다.
`app` 모듈을 구현합니다.
기존 기능 구현 및 구동 준비
=> feat: 도어락 비밀번호 관련 컨트롤러 구현 및 모듈 추가

src/app/AppModule.ts, src/app/application/user/query/listUser/ListUserQueryHandler.ts, src/app/interface/user/manager/UserManageController.ts, src/app/interface/user/manager/dto/ListUserRequestDto.ts
회원 목록 조회 기능이 정상적으로 동작하도록 수정합니다.
여러 문제로 실제로 서버를 구동시켰을 때 정상적으로 동작하지 않고 있었습니다.
=> fix: 회원 목록 조회 기능이 정상적으로 동작하도록 수정

src/app/application/user/query/listUser/ListUserQuery.ts, src/app/application/user/query/listUser/ListUserQueryHandler.ts, src/app/domain/user/model/Profile.ts, src/app/interface/user/manager/UserManageController.ts, src/app/interface/user/manager/dto/ListUserRequestDto.ts
전화번호 및 학번 검색어 유형을 추가합니다.
니즈가 발생하였음.
=> feat: 전화번호 및 학번 검색어 유형 추가

eslint.config.mjs, jest/setup.ts, package.json, src/app/domain/user/model/User.spec.ts, src/app/domain/user/model/User.ts, src/main.ts, yarn.lock
회원 인증 필요 여부 판단 메서드를 구현합니다.
필요합니다.
=> feat: 회원 인증 필요 여부 판단 메서드 구현

src/app/application/user/query/listUser/ListUserQueryHandler.ts, src/app/application/user/query/listUser/ListUserQueryResult.ts, src/app/application/user/query/view/UserListView.ts, src/app/application/user/query/view/UserView.ts, src/app/interface/user/manager/dto/ListUserResponseDto.ts, src/app/interface/user/manager/dto/common/UserResponse.ts
유저 목록 응답에 태그를 추가합니다.
UI 상에 드러내야 하는데, 관련 계산을 프론트엔드보단 백엔드에서 진행하는 것이 더 적절합니다.
=> feat: 유저 목록 응답에 태그 추가

src/__test__/fixtures/domain/user.ts, src/app/domain/user/model/User.spec.ts, src/app/domain/user/model/User.ts
회비 납부 대상 여부 판단 메서드를 구현합니다.
N/A
=> feat: 회비 납부 대상 여부 판단 메서드 구현

src/app/application/user/query/listUser/ListUserQueryHandler.ts
회원 목록에서 태그를 반환하도록 추가합니다.
기존 기능 구현
=> feat: 회원 목록에 태그 추가

docker-compose.yaml, mikro-orm.config.ts
개발 환경에서 한글이 깨지는 문제를 수정합니다.
한글 데이터를 넣으면 한글이 깨집니다. 이를 수정합니다.
=> fix: 개발 환경에서 한글이 깨지는 문제 수정

src/app/application/user/query/listUser/ListUserQueryHandler.ts, src/app/domain/fee/model/FeeHistory.ts, src/main.ts
회원 목록 조회가 정상적으로 동작하도록 수정합니다.
의도와 다르게 동작하지 않고 있었습니다.
=> fix: 회원 목록 조회가 정상적으로 동작하도록 수정

.env.development, package-lock.json, package.json, src/app/AppModule.ts, src/app/interface/user/discord/UserDiscordEventHandler.ts, src/core/config/DiscordConfig.ts, src/core/core.module.ts, src/core/discord/DiscordClient.ts, src/core/discord/DiscordEventConsumer.ts, src/core/discord/DiscordEventHandler.ts, src/core/discord/DiscordEventHandlerContainer.ts, src/core/discord/DiscordModule.ts, src/main.ts
디스코드 이벤트 핸들러를 구현합니다.
디스코드와 연동 시 디스코드의 이벤트를 받을 일이 여럿 있을 가능성이 높아 이에 대한 핸들러를 쉽게 구현할 수 있도록 합니다.
=> feat: 디스코드 이벤트 핸들러 구현

package-lock.json, package.json
빌드 전 dist 디렉토리를 제거합니다.
dist가 온전하게 만들어지지 않는 문제가 있습니다.
=> chore: 빌드 전 dist 디렉토리 제거
