khu-khlug/sight-backend

src/__test__/fixtures/domain.ts
src/__test__/fixtures/view.ts
src/app.module.ts
src/app/application/user/query/IUserQuery.ts
src/app/application/user/query/listUser/ListUserQuery.ts
src/app/application/user/query/listUser/ListUserQueryHandler.spec.ts
src/app/application/user/query/listUser/ListUserQueryHandler.ts
src/app/application/user/query/listUser/ListUserQueryResult.ts
src/app/domain/user/model/User.spec.ts
src/app/domain/user/model/User.ts

관심 분야로 멤버 목록을 조회할 수 있도록 쿼리 조건으로 `interest`를 추가하였습니다.
또한, import 문에 대해 린트를 적용하였습니다.
그리고, `AppModule`에서 이미 삭제된 서비스인 `AppService`를 참조하는 부분을 수정하였습니다.
레거시에서 그러한 기능이 있습니다.
그 외 두 가지는 코드 정리 용도입니다.

feat: 관심 분야로 멤버 목록을 조회할 수 있도록 쿼리 조건 추가

---

src/__test__/fixtures/domain.ts
src/__test__/fixtures/view.ts
src/app/application/interest/query/IInterestQuery.ts
src/app/application/interest/query/listInterest/ListInterestQuery.ts
src/app/application/interest/query/listInterest/ListInterestQueryHandler.spec.ts
src/app/application/interest/query/listInterest/ListInterestQueryHandler.ts
src/app/application/interest/query/listInterest/ListInterestQueryResult.ts
src/app/application/interest/query/view/InterestListView.ts
src/app/application/interest/query/view/InterestView.ts
src/app/application/user/query/view/UserView.ts
src/app/domain/interest/model/Interest.ts
src/app/domain/user/model/Profile.ts

관심 분야 도메인(`Interest`)을 추가하였고, 관심 분야 목록 쿼리를 추가하였습니다.
그리고 유저의 필드에서 `interest`를 제거하였습니다. 이후 `UserInterest` 등의 이름을 가진 테이블로 연결할 예정입니다.
**후속 조치에 대한 관련 이슈**
- #9 
레거시 기능에 유저 수정 등에서 현재의 관심 분야 목록을 조회하는 파트가 있습니다. 이를 위해 사용합니다.

feat: 관심 분야 도메인 추가 및 쿼리 추가

---

.github/workflows/coverage.yml
.github/workflows/test.yml
codecov.yml
src/app/application/user/command/updateUser/UpdateUserCommand.ts

커버리지 툴을 codecov에서 [jest-coverage-report-action](https://github.com/ArtiomTr/jest-coverage-report-action)으로 변경합니다.
codecov는 시트가 많아지면 유료가 됩니다. 따라서 깃헙 액션 중 jest-coverage-report-action으로 대체합니다.

chore: 커버리지 툴 변경

---

src/app/application/user/command/updateUser/UpdateUserCommandHandler.spec.ts
src/app/application/user/command/updateUser/UpdateUserCommandHandler.ts
src/app/domain/adapter/ISlackSender.ts

유저 정보 변경 시 슬랙 메시지를 전송하도록 수정합니다.
유저 정보가 변경되면 기존에는 슬랙 메시지가 전송되었습니다.

fix: 유저 정보 변경 시 슬랙 메시지를 전송하도록 수정

---

src/app/application/interest/query/listInterest/ListInterestQueryHandler.spec.ts
src/app/application/user/command/updateUnitedUser/UpdateUnitedUserComandHandler.spec.ts
src/app/application/user/command/updateUnitedUser/UpdateUnitedUserCommand.ts
src/app/application/user/command/updateUnitedUser/UpdateUnitedUserCommandHandler.ts
src/app/application/user/command/updateUnitedUser/UpdateUnitedUserCommandResult.ts
src/app/application/user/command/updateUser/UpdateUserCommandHandler.spec.ts
src/app/application/user/command/updateUser/UpdateUserCommandHandler.ts
src/app/application/user/eventHandler/UserProfileUpdatedHandler.spec.ts
src/app/application/user/eventHandler/UserProfileUpdatedHandler.ts
src/app/application/user/query/listUser/ListUserQueryHandler.spec.ts
src/app/domain/adapter/ISlackSender.ts
src/app/domain/interest/IInterestRepository.ts
src/app/domain/interest/UserInterestFactory.spec.ts
src/app/domain/user/IUserRepository.ts
src/app/domain/user/event/UserProfileUpdated.ts
src/app/domain/user/model/User.spec.ts
src/app/domain/user/model/User.ts
src/constant/message.ts
src/main.ts

교류 회원 정보를 수정하는 커맨드 핸들러(`UpdateUnitedUserCommandHandler`)를 구현하고 관련 테스트를 추가하였습니다.
또한, 유저 정보가 변경되었을 때 슬랙 메시지 보내는 부분을 이벤트 핸들러로 옮겼습니다.
유저 정보 변경이 발생했을 때, 공통적으로 슬랙 메시지가 전송됩니다. 해당 로직을 이벤트 핸들러로 묶어서 처리하도록 수정합니다.

feat: 교류 회원 정보 수정 핸들러 구현 및 이벤트 핸들러 구현

---

src/__test__/fixtures/domain.ts
src/__test__/fixtures/view.ts

`faker.phone.number(format: string)`이 deprecated되어, 이를 수정합니다.
해당 함수가 deprecate되어서.

test: deprecated된 faker 함수 수정

---

.dockerignore
Dockerfile
docker-compose.yaml
src/core/persistence/transaction/Transactional.spec.ts

도커 관련 파일을 생성합니다.
이후에 mysql 등 DB도 같이 사용해야 하는데, 로컬에서 개발할 때 따로 mysql을 띄우면 불편함이 있습니다.
따라서 미리 docker compose 파일을 정의합니다.
또, 배포 시에 ECS를 활용할 예정이기 때문에 컨테이너화 하는 목적도 있습니다.

build: 도커 관련 파일 생성

---

src/app/application/user/query/IUserQuery.ts
src/app/application/user/query/listUser/ListUserQuery.ts
src/app/application/user/query/listUser/ListUserQueryHandler.spec.ts
src/app/application/user/query/listUser/ListUserQueryHandler.ts

관심사의 id로 쿼리하도록 수정합니다.
관심사 문자열로 비교하는 것이 아니라 `UserInterest` 도메인 기준으로 쿼리할 것이기 때문에, `interest` 대신에 `interestId`를 받도록 수정합니다.

fix: 관심사의 id로 쿼리하도록 수정

---

src/app/application/group/query/IGroupQuery.ts
src/app/application/group/query/listGroup/ListGroupQuery.ts
src/app/application/group/query/listGroup/ListGroupQueryHandler.spec.ts
src/app/application/group/query/listGroup/ListGroupQueryHandler.ts

그룹을 관심사 id로 쿼리할 수 있도록 구현합니다.
기존 기능을 구현합니다.

feat: 그룹을 관심사 id로 쿼리할 수 있도록 구현

---

src/app/application/group/command/changeGroupState/ChangeGroupStateCommand.ts
src/app/application/group/command/changeGroupState/ChangeGroupStateCommandHandler.spec.ts
src/app/application/group/command/changeGroupState/ChangeGroupStateCommandHandler.ts
src/app/application/group/command/changeGroupState/ChangeGroupStateCommandResult.ts
src/app/application/group/eventHandler/GroupStateChangedHandler.ts
src/app/domain/group/event/GroupStateChanged.ts
src/app/domain/group/model/Group.spec.ts
src/app/domain/group/model/Group.ts
src/app/domain/group/model/constant.ts
src/app/domain/user/IUserRepository.ts
src/app/domain/user/model/User.ts
src/constant/message.ts
src/constant/point.ts

그룹 변경 커맨드 핸들러를 구현합니다.
그리고 관련 이벤트와 그 핸들러를 구현합니다.
기존 기능의 호환을 위함입니다.

feat: 그룹 변경 커맨드 핸들러 구현

---

src/app/domain/group/IGroupLogger.ts
src/app/infra/logger/GroupLogger.spec.ts
src/app/infra/logger/GroupLogger.ts
src/core/auth/AuthGuard.ts

더 편하게 `GroupLog`를 생성하여 저장하기 위해 `GroupLogger`를 구현합니다.
Fixes https://github.com/khu-khlug/sight-backend/issues/46

feat: 그룹 로거 구현

---

src/app/application/group/command/disablePortfolio/DisablePortfolioCommand.ts
src/app/application/group/command/disablePortfolio/DisablePortfolioCommandHandler.spec.ts
src/app/application/group/command/disablePortfolio/DisablePortfolioCommandHandler.ts
src/app/application/group/eventHandler/GroupCreatedHandler.ts
src/app/application/group/eventHandler/GroupPortfolioDisabledHandler.spec.ts
src/app/application/group/eventHandler/GroupPortfolioDisabledHandler.ts
src/app/application/group/eventHandler/GroupPortfolioEnabledHandler.ts
src/app/application/group/eventHandler/GroupStateChangedHandler.ts
src/app/application/group/eventHandler/GroupUpdatedHandler.ts
src/app/application/user/eventHandler/UserProfileUpdatedHandler.ts
src/app/domain/adapter/ISlackSender.ts
src/app/domain/group/event/GroupPortfolioDisabled.ts
src/app/domain/group/model/Group.spec.ts
src/app/domain/group/model/Group.ts
src/constant/template.ts
src/core/message/MessageBuilder.spec.ts

그룹 포트폴리오 비활성화 기능을 구현합니다.
또, `ISlackSender`의 `send`에서 `sourceUserId`를 선택적으로 받도록 수정하였습니다.
기존 기능입니다.

feat: 그룹 포트폴리오 비활성화 구현

---

src/__test__/fixtures/domain/group.ts
src/app/application/group/command/addBookmark/AddBookmarkCommand.ts
src/app/application/group/command/addBookmark/AddBookmarkCommandHandler.spec.ts
src/app/application/group/command/addBookmark/AddBookmarkCommandHandler.ts
src/app/application/group/command/disablePortfolio/DisablePortfolioCommandHandler.ts
src/app/application/group/eventHandler/GroupBookmarkCreatedHandler.spec.ts
src/app/application/group/eventHandler/GroupBookmarkCreatedHandler.ts
src/app/domain/group/GroupBookmarkFactory.spec.ts
src/app/domain/group/GroupBookmarkFactory.ts
src/app/domain/group/IGroupBookmarkRepository.ts
src/app/domain/group/event/GroupBookmarkCreated.ts
src/constant/message.ts
src/constant/template.ts

그룹 즐겨찾기 추가 기능을 구현합니다.
기존 기능을 구현합니다.

feat: 그룹 즐겨찾기 추가 구현

---

src/app/application/group/command/addBookmark/AddBookmarkCommandHandler.spec.ts
src/app/application/group/command/addBookmark/AddBookmarkCommandHandler.ts
src/app/application/group/command/removeBookmark/RemoveBookmarkCommand.ts
src/app/application/group/command/removeBookmark/RemoveBookmarkCommandHandler.spec.ts
src/app/application/group/command/removeBookmark/RemoveBookmarkCommandHandler.ts
src/app/application/group/eventHandler/GroupBookmarkCreatedHandler.spec.ts
src/app/application/group/eventHandler/GroupBookmarkCreatedHandler.ts
src/app/application/group/eventHandler/GroupBookmarkRemovedHandler.spec.ts
src/app/application/group/eventHandler/GroupBookmarkRemovedHandler.ts
src/app/domain/group/event/GroupBookmarkCreated.ts
src/app/domain/group/event/GroupBookmarkRemoved.ts
src/app/domain/group/model/GroupBookmark.ts
src/constant/message.ts
src/constant/template.ts

그룹 즐겨찾기 해제 기능을 구현합니다.
기존 기능을 구현합니다.

feat: 그룹 즐겨찾기 해제 기능 구현

---

.github/workflows/coverage.yml
.github/workflows/test.yml

required workflow로 단순 테스트만 하도록 수정합니다.
커버리지 계산이 시간이 적지 않게 걸립니다. 결국 확인이 필요한 건 테스트 성공 여부지 커버리지는 아니라서 테스트만 성공하면 머지가 가능하도록 수정합니다.

ci: required workflow로 단순 테스트만 하도록 수정

---

.gitignore
package-lock.json
package.json
src/core/auth/AuthGuard.ts
src/core/auth/ITokenVerifier.ts
src/core/auth/LaravelAuthnAdapter.ts
src/core/auth/UserRole.ts
src/core/config/LaravelSessionConfig.ts
src/core/config/index.ts

인증 단계에서 라라벨 세션을 공유하도록 구현합니다.
- `LaravelAuthnAdapter`를 구현하여 세션 정보로 요청자의 유저 ID를 가져올 수 있도록 구현합니다.
- `AuthGuard`에서 해당 어댑터를 활용하여 유저 정보를 가져오도록 구현합니다.
점진적 마이그레이션을 위해 기존 시스템인 라라벨과 인증 체계를 공유할 필요가 있습니다.

feat: 인증 단계에서 라라벨 세션을 공유하도록 구현

---

.github/workflows/coverage.yml

`actions/checkout`, `actions/setup-node`의 버전을 업그레이드합니다.
버전 차이로 인해 cache 처리에서 불필요하게 긴 시간이 소요됩니다. 관련 버그를 해결하기 위해 버전을 업그레이드합니다.
- https://github.com/actions/setup-node/issues/878

ci: checkout, setup-node 액션의 버전 업그레이드

---

src/core/auth/Auth.ts
src/core/auth/AuthGuard.spec.ts
src/core/auth/AuthGuard.ts

`@Auth()` 데코레이터를 구현하고, 가드에 반영합니다.
인터페이스 계층에서의 인증/인가 처리를 위해

feat: auth 데코레이터 구현 및 가드 완성

---

src/app/application/infraBlue/command/updateDoorLockPassword/UpdateDoorLockPasswordCommandHandler.spec.ts
src/app/application/infraBlue/command/updateDoorLockPassword/UpdateDoorLockPasswordCommandHandler.ts
src/app/application/infraBlue/query/ICacheQuery.ts
src/app/application/infraBlue/query/getDoorLockPassword/GetDoorLockPasswordQueryHandler.spec.ts
src/app/application/infraBlue/query/getDoorLockPassword/GetDoorLockPasswordQueryHandler.ts
src/app/application/infraBlue/query/getDoorLockPassword/GetDoorLockPasswordQueryResult.ts
src/app/application/infraBlue/query/view/DoorLockPasswordView.ts
src/app/domain/cache/model/Cache.ts

쿼리 인터페이스 대신 레포지토리를 사용하도록 수정하였습니다.
또, 캐시 아이디를 캐시 모델에서 관리하도록 수정하였습니다.
복잡성으로 인해 얻을 수 있는 것보다 불필요하게 계층이 나뉘면서 오는 트레이드 오프가 더 크다고 판단하였습니다.

fix: 쿼리 인터페이스 대신 레포지토리를 사용하도록 수정

---

src/core/auth/AuthGuard.spec.ts
src/core/auth/AuthGuard.ts
src/core/auth/AuthModule.ts
src/core/core.module.ts

`AuthGuard`를 적용한 `AuthModule`을 `CoreModule`에 포함시킵니다.
1. `AuthModule`이 등록되지 않아 `AuthGuard`가 동작하지 않았습니다.
2. `User` 모델이 엔티티로써 정의되지 않아 레포지토리에서 불러올 수 없는 문제가 있어, 임시적으로 raw query로 대체하였습니다.

fix: auth guard 적용

---

src/app/domain/cache/model/Cache.ts
src/core/auth/AuthGuard.ts

1. 유저 테이블명을 `khlug_member`에서 `khlug_members`로 수정합니다.
2. 기존 레거시 데이터베이스의 테이블 정의를 따라가기 위해 `Cache` 모델의 `id` 타입을 정수로 수정합니다.
1. 프로덕션에서 실행 시 500 에러가 발생합니다.
2. 데이터를 찾지 못하고 있습니다.

fix: 일부 버그 수정

---

src/core/config/AppConfig.ts
src/core/config/index.ts
src/main.ts

프로덕션 환경에서는 특정 origin만 CORS가 허용되도록 수정합니다.
axios에서 `withCredentials`를 통해 쿠키와 함께 요청을 보내면, 서버의 응답 헤더에서 `Access-Control-Allow-Origin`의 값에 와일드카드를 사용하는 경우 보안 문제로 CORS 에러를 일으킵니다. 따라서, 프로덕션 환경에서는 특정 도메인만 허용하도록 합니다.
```
Access to XMLHttpRequest at 'https://api.khlug.org/manager/door-lock-password' from origin 'https://app.khlug.org' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

fix: 프로덕션 환경에서는 특정 Origin만 참조하도록 수정

---

src/main.ts

`Access-Control-Allow-Credentials` 응답 헤더로 `true` 값을 보내도록 수정합니다.
`withCredentials: true`인 경우 해당 헤더가 `true`일 때만 정상 동작한다는 CORS 에러가 발생하여, 이를 해결하기 위함입니다.

fix: Access-Control-Allow-Credentials 응답 헤더에 true 포함

---

src/app/domain/cache/model/Cache.ts

`Cache` 테이블의 `updatedAt` 컬럼 이름을 `camelCase`에서 `snake_case`로 수정합니다.
현재 프로덕션 DB의 컬럼 이름이 `snake_case`로 되어 있습니다.

fix: 컬럼 이름의 case 수정

---

src/app/domain/user/model/Profile.ts
src/app/domain/user/model/User.ts
src/core/persistence/Entities.ts

의도와 다르게 생성되는 유저 엔티티의 컬럼 정보를 수정합니다.
또한, `EntityModels`에 유저 엔티티를 추가합니다.
유저 엔티티가 현재 데이터베이스에 생성된 유저 테이블의 형태와 다르게 나오는 문제가 있습니다.

fix: 유저 엔티티 수정 및 등록

---

.swcrc
docker-compose.yaml
package.json
yarn.lock

mikro-orm shcema update를 쉽게 할 수 있도록 수정합니다.
`mikro-orm.config.ts`가 타입스크립트 파일이라 mikro-orm CLI가 인식하지 못합니다. 따라서 `ts-node`와 `tsconfig-paths`를 활용하여 쉽게 실행할 수 있도록 수정합니다.

chore: mikro-orm schema update를 쉽게 할 수 있도록 수정

---

src/app/application/user/query/view/UserView.ts
src/app/interface/user/manager/dto/ListUserResponseDto.ts
src/app/interface/user/manager/dto/common/UserResponse.ts

유저 목록 응답에서 비밀번호를 제거합니다.
비밀번호는 응답에 포함되어도 불필요하고, 해시 처리가 되어 있긴 하나 보안 문제가 발생할 수 있으므로 응답에서 제거합니다.

fix: 유저 목록 응답에서 비밀번호 제거

---

src/__test__/fixtures/domain/group.ts
src/__test__/fixtures/view/user.ts
src/app/domain/group/GroupLogFactory.spec.ts
src/app/domain/group/model/GroupLog.ts
src/app/infra/logger/GroupLogger.spec.ts
src/core/auth/AuthGuard.spec.ts

유저 id 타입이 `string`에서 `number`로 변경됨에 따라 발생한 타입 에러를 수정합니다.
관련 PR: #89 
N/A

fix: 유저 id 타입 변경에 따른 타입 에러 수정

---

src/__test__/fixtures/domain/user.ts
src/__test__/fixtures/view/user.ts
src/app/application/user/command/updateUnitedUser/UpdateUnitedUserCommandHandler.spec.ts
src/app/application/user/command/updateUser/UpdateUserCommandHandler.spec.ts
src/app/application/user/query/listUser/ListUserQuery.ts
src/app/application/user/query/listUser/ListUserQueryHandler.ts
src/app/application/user/query/view/UserView.ts
src/app/domain/user/model/User.spec.ts
src/app/domain/user/model/User.ts
src/app/domain/user/model/constant.ts
src/app/interface/user/manager/UserManageController.ts
src/app/interface/user/manager/dto/ListUserRequestDto.ts
src/app/interface/user/manager/dto/ListUserResponseDto.ts
src/app/interface/user/manager/dto/common/UserResponse.ts

`state`를 `studentStatus`로, `active`를 `status`로 수정하였습니다.
`state`는 학적 상태를 나타내고 있습니다. 따라서 `studentStatus`로 수정하였습니다.
또한, `active`의 실제 데이터를 살펴보니 `-1, 0, 1` 3개의 값을 가지며 true / false flag가 아니었습니다. 따라서 이를 반영하여 `UserStatus`를 정의하고 적용하였습니다.

fix: state 및 active 프로퍼티의 이름을 적절하게 수정

---

jest/setup.ts
src/__test__/fixtures/domain/user.ts
src/app/domain/user/model/User.spec.ts
src/app/domain/user/model/User.ts
src/main.ts
src/util/univDate.spec.ts
src/util/univDate.ts
src/util/univPeriod.spec.ts
src/util/univPeriod.ts
src/util/univTerm.spec.ts
src/util/univTerm.ts

잘못된 회비 납부 대상 판단 로직을 수정하고 관련 테스트 케이스를 추가합니다.
`"가입한지 1년이 지나지 않았음" OR "4학년 미만임"`인 경우 납부 대상인데, 의도와 다르게 동작하고 있었습니다.
또, 방학 내 가입자에 대한 케이스 처리를 추가합니다.

fix: 잘못된 회비 납부 대상 판단 로직 수정

---

docker-compose.yaml
mikro-orm.config.ts
src/app/domain/user/model/Profile.ts
src/app/domain/user/model/User.ts
src/util/mikro-orm/LegacyDateConverter.ts

non-standard인 레거시 날짜 데이터(`0000-00-00 00:00:00`)를 처리할 수 있도록 컨버터를 추가하고 적용합니다.
이후에는 해당하는 데이터를 `NULL`로 관리 할 예정입니다.
기존 데이터를 갖고 운영 중인 PHP 로직이 있기 때문에, 데이터를 함부로 바꿀 수는 없습니다.
따라서, 관련 mysql 설정 및 mikro-orm 컬럼 설정을 수정하였습니다.

fix: non-standard인 레거시 날짜 데이터를 처리할 수 있도록 수정

---

eslint.config.mjs

`eslint.config.mjs` 내의 `tsconfigRootDir`를 `./`로 변경합니다.
기존 해당 속성이 maintainer분의 절대경로로 작성되어 있어, 다른 기여자의 PC에서 로드되지 않는 문제가 발생해 상대경로로 변경하였습니다. (Issue #108)

chore: tsconfigRootDir를 상대경로로 변경

---

src/core/discord/DiscordClient.ts

디스코드 봇 토큰이 존재하지 않으면 디스코드로 연결하지 않도록 수정합니다.
로컬 개발 시 디스코드 기능을 개발하지 않더라도 디스코드 봇 토큰이 존재하지 않으면 로그인이 실패하여 서버가 켜지지 않는 문제가 있습니다. 이를 해결하기 위해 토큰이 존재하지 않는 경우 `Client@login`을 수정하지 않도록 수정하였습니다.

fix: 디스코드 봇 토큰이 존재하지 않으면 디스코드로 연결하지 않도록 수정

---

src/app/AppModule.ts
src/app/application/user/command/createDiscordIntegration/CreateDiscordIntegrationCommandHandler.spec.ts
src/app/application/user/command/createDiscordIntegration/CreateDiscordIntegrationCommandHandler.ts
src/app/application/user/command/deleteUser/DeleteUserCommand.ts
src/app/application/user/command/deleteUser/DeleteUserCommandHandler.spec.ts
src/app/application/user/command/deleteUser/DeleteUserCommandHandler.ts
src/app/application/user/command/removeDiscordIntegration/RemoveDiscordIntegrationCommandHandler.spec.ts
src/app/application/user/command/removeDiscordIntegration/RemoveDiscordIntegrationCommandHandler.ts
src/app/application/user/service/DiscordMemberService.spec.ts
src/app/application/user/service/DiscordMemberService.ts
src/app/domain/discord/IDiscordIntegrationRepository.ts
src/app/domain/user/model/User.ts
src/app/infra/discord/DiscordApiAdapter.ts
src/app/infra/persistence/repository/DiscordIntegrationRepository.ts
src/app/infra/persistence/repository/mapper/DiscordIntegrationMapper.ts
src/app/interface/user/public/UserController.ts
src/constant/message.ts

회원 탈퇴 기능을 구현합니다.
회원 탈퇴 시 디스코드 연동 정보를 제거해야 하는 상황인데, 회원 탈퇴 기능이 현재 레거시 서버에 구현되어 있으므로 이를 옮깁니다.

feat: 회원 탈퇴 기능 구현

---

src/app/AppModule.ts
src/app/application/user/command/graduateUser/GraduateUserCommand.ts
src/app/application/user/command/graduateUser/GraduateUserCommandHandler.spec.ts
src/app/application/user/command/graduateUser/GraduateUserCommandHandler.ts
src/app/domain/user/model/User.spec.ts
src/app/domain/user/model/User.ts
src/app/interface/user/public/UserController.ts
src/constant/message.ts

회원 졸업 처리를 구현합니다.
졸업 신고 시 디스코드 연동 정보를 갱신해야 하는 상황인데, 회원 탈퇴 기능이 현재 레거시 서버에 구현되어 있으므로 이를 옮깁니다.

feat: 회원 졸업 처리 기능 구현

---

src/app/AppModule.ts
src/app/infra/notification/CachedDiscordUserIdMapper.spec.ts
src/app/infra/notification/CachedDiscordUserIdMapper.ts
src/app/infra/notification/IDiscordUserIdMapper.ts

로컬 캐싱이 적용된 디스코드 유저 아이디 매퍼를 구현합니다.
- 메시지 전송 시 사이트 시스템 내 유저의 아이디는 알고 있지만 디스코드 유저의 아이디는 알 수 없습니다.
- 따라서, 메시지 전송 시 이러한 것들을 신경쓰지 않도록 메시지 전송 시 매핑하여 전송하도록 구현할 예정입니다.
- 이때, 디스코드 연동 정보는 왠만해서는 변하지 않으므로 1시간 단위로 캐시를 적용하여 속도 증가 및 쿼리 횟수를 감소시킵니다.

feat: 캐싱이 적용된 디스코드 유저 아이디 매퍼 구현

---

src/app/AppModule.ts

클래스를 모듈에 등록할 때 `useValue` 대신 `useClass`를 사용하도록 수정합니다.
실수로 `useValue`를 넣어 주입이 의도와 다르게 되고 있던 문제가 있었습니다.

fix: 모듈에 등록 시 use class를 사용하도록 수정

---

.github/workflows/build.yaml

컨테이너 이미지를 arm arch 기준으로 빌드하도록 수정합니다.
컨테이너 실행 환경이 `arm64`(`t4g`)입니다. 하지만 생략하면 `amd` arch로 빌드되기 때문에, 정상적으로 실행되지 않습니다.

chore: 컨테이너 이미지를 arm architecture 기준으로 빌드하도록 수정

---

src/core/core.module.ts
src/core/health/HealthController.ts

헬스 체크 api를 구현합니다. 간단하게 서버가 살아있는지만 확인하기 위해 핑퐁 API로만 구현합니다.
ECS 등 서비스 상태를 알아내야 할 때가 있습니다. 이때 서버가 정상적으로 요청을 처리할 수 있는지를 확인하기 위해 헬스 체크 api를 구현하였습니다.

feat: 헬스 체크 api 구현
